#!/usr/bin/perl
use strict;
use warnings;
use App::MyPort::CLI;

App::MyPort::CLI->run;

__END__

=encoding utf8

=head1 NAME

myport - my own ports like system

=head1 SYNOPSIS

    % myport install nginx
    % myport list

=head1 DESCRIPTION

myport is my own ports like package management system.

=head1 ENVIRONMENT VARIABLES

=over 4

=item MYPORT_ROOT

choose your root directory.default value is '/usr/local/app/'.

=item MYPORT_LOCALDIR

choose your local directory.default value is '/usr/local/'.

=item MYPORT_SPEC_GITREPO

myport spec repository.

=back

=head1 AUTHOR

Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF GMAIL COME<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
